# **Практическая работа № 2. Предобработка даннных.**

Группа:

ФИО:

## **Iris Dataset**

Набор данных Iris был представлен миру британским статистиком и генетиком Рональдом Фишером в 1936 году в его революционной статье "The use of multiple measurements in taxonomic problems". Фишер использовал этот набор для демонстрации линейного дискриминантного анализа — методики, которая спустя почти столетие продолжает оставаться актуальной и эффективной.

Данные были собраны биологом Эдгаром Андерсоном на полуострове Гаспе в Канаде. Он измерил четыре характеристики у 150 экземпляров ирисов трёх видов: Iris setosa, Iris versicolor и Iris virginica. Этот простой и изящный набор данных заложил основы для множества алгоритмов машинного обучения, которые мы используем сегодня.

Ключевые причины, по которым Iris dataset стал эталоном в машинном обучении:

Идеальный размер: 150 образцов — достаточно для анализа, но не настолько много, чтобы вызвать проблемы производительности

Сбалансированные классы: по 50 образцов каждого вида, что создаёт идеальные условия для обучения

Многомерность: четыре признака позволяют исследовать многомерные отношения

Различимость классов: один класс (Setosa) линейно отделим, а два других (Versicolor и Virginica) частично перекрываются, создавая интересную задачу для алгоритмов

В настоящее время исследователи и аналитики данных продолжают использовать Iris dataset как отправную точку для обучения и тестирования новых алгоритмов.

Набор данных Iris состоит из 150 образцов ирисов, разделенных на три вида. Каждый образец характеризуется четырьмя признаками: длиной и шириной чашелистика (sepal length and width), а также длиной и шириной лепестка (petal length and width). Все измерения представлены в сантиметрах.

## **Изучение данных из файла**

Загрузка данных и проверка структуры (типы признаков, размерность, форматы).

Ипортируем библитеку pandas

In [2]:
import pandas as pd

Считываем данные из файла .csv и сохраняем в переменной df

In [3]:
# df = pd.read_csv("iris_teach.csv")
df = pd.read_csv("https://kalitvin.github.io/notebooks/iris/iris_teach.csv")

Получим первые 10 строк таблицы с данными

In [4]:
df.head(10)

,Id,Sepal Length Cm,Sepal Width (Cm),Petal-Length-Cm,Petal-WIDTH(Cm),SPECIES,unit
0,1,??,3.5,1.4,0.2,Iris-setosa,cm
1,2,very_long,3.0,1.4,0.2,Iris-setosa,cm
2,3,NaN,3.2,1.3,0.2,Iris-setosa,cm
3,4,4.6,3.1,1.5,0.2,Iris-setosa,cm
4,5,5.0,3.6,1.4,0.2,Iris-setosa,cm
5,6,5.4,3.9,1.7,0.4,setsoa,cm
6,7,4.6,3.4,1.4,0.3,Iris-setosa,cm
7,8,5.0,3.4,1.5,0.2,Iris-setosa,cm
8,9,4.4,2.9,NaN,0.2,Iris-setosa,cm
9,10,4.9,3.1,1.5,0.1,Iris-setosa,cm

Получим информацию о таблице с данными

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 185 entries, 0 to 184
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Id                185 non-null    int64
 1   Sepal Length Cm   170 non-null    str
 2   Sepal Width (Cm)  185 non-null    float64
 3   Petal-Length-Cm   171 non-null    float64
 4   Petal-WIDTH(Cm)   185 non-null    float64
 5   SPECIES           185 non-null    str
 6   unit              185 non-null    str
dtypes: float64(3), int64(1), str(3)
memory usage: 10.2 KB

В таблице 6 колонок:
 * 0 Id — Порядковый номер.
   (тип данных int64 - целое число).
 * 1 SepalLengthCm - Длина чашелистика (наружный лепесток цветка) в сантиметрах. Это числовой признак, отражающий общий размер цветка по одной из осей.
*  (тип данных float64 - вещественное число).
 * 2 SepalWidthCm - Ширина чашелистика в сантиметрах. Ещё один линейный размер цветка; вместе с длиной образует грубую характеристику «размера и формы» цветка.,
   (тип данных float64 - вещественное число)
 * 3 PetalLengthCm - Длина лепестка в сантиметрах. Очень информативный признак для разделения видов: у Iris setosa лепестки существенно короче, чем у двух других видов.,
   (тип данных float64 - вещественное число)
 * 4 PetalWidthCm - Ширина лепестка в сантиметрах. В связке с длиной лепестка позволяет почти идеально разделить три вида (особенно отделить setosa).,
   (тип данных float64 - вещественное число)
 * 5 Species - Вид ириса (целевая переменная для классификации):
   setosa; versicolor; virginica.
   (тип данных object - строка)

В sklearn по умолчанию data содержит только 4 числовых признака, а target — это массив из 0, 1, 2, соответствующих этим трём видам; имена видов лежат в target_names. Если загружать с as_frame=True, в frame появится сразу и признаки, и столбец вида.

In [6]:
df.columns

Index(['Id', 'Sepal Length Cm', 'Sepal Width (Cm)', 'Petal-Length-Cm',
       'Petal-WIDTH(Cm)', 'SPECIES', 'unit'],
      dtype='str')

В sklearn по умолчанию data содержит только 4 числовых признака, а target — это массив из 0, 1, 2, соответствующих этим трём видам; имена видов лежат в target_names. Если загружать с as_frame=True, в frame появится сразу и признаки, и столбец вида.

### **Название колонок**

**Базовые принципы**

Осмысленные имена. Название должно описывать, что в колонке лежит: sepal_length, body_mass_g, crop_yield_t_ha, а не x1, col3.

Единый стиль по всему проекту. Не мешать sepalLength, Sepal_length и sepal_length в одном датасете.

Без пробелов и спецсимволов. Лучше sepal_length вместо Sepal length (cm) — проще писать код и меньше сюрпризов при merge/SQL.

Рекомендуемый стиль
В Python‑экосистеме обычно берут:

snake_case:

всё в нижнем регистре;

слова разделены подчёркиваниями: sepal_length, petal_width, student_age.

Дополнительно (по желанию команды/курса):

Префиксы по типу данных: n_ для чисел, c_ для категорий и т.п. (n_area, c_species) — удобно в больших ML‑таблицах.
​

Единицы измерения в имени: sepal_length_cm, yield_t_ha, body_mass_g.

Чего лучше избегать
Пробелы, дефисы, скобки: Sepal length (cm), petal-length. Лучше sepal_length_cm.

Очень короткие аббревиатуры, понятные только автору (sl, pl без контекста).

**Корректировка названий колонок**

In [7]:
def clean_data(df):
    # Rename column 'Id' to 'id'
    df = df.rename(columns={'Id': 'id'})
    # Rename column 'Sepal Length Cm' to 'sepal_length_cm'
    df = df.rename(columns={'Sepal Length Cm': 'sepal_length_cm'})
    # Rename column 'Sepal Width (Cm)' to 'sepal_width_cm'
    df = df.rename(columns={'Sepal Width (Cm)': 'sepal_width_cm'})
    # Rename column 'Petal-Length-Cm' to 'petal_length_cm'
    df = df.rename(columns={'Petal-Length-Cm': 'petal_length_cm'})
    # Rename column 'Petal-WIDTH(Cm)' to 'petal_width_cm'
    df = df.rename(columns={'Petal-WIDTH(Cm)': 'petal_width_cm'})
    # Rename column 'SPECIES' to 'species'
    df = df.rename(columns={'SPECIES': 'species'})
    return df

df = clean_data(df.copy())
df.head()

,id,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,species,unit
0,1,??,3.5,1.4,0.2,Iris-setosa,cm
1,2,very_long,3.0,1.4,0.2,Iris-setosa,cm
2,3,NaN,3.2,1.3,0.2,Iris-setosa,cm
3,4,4.6,3.1,1.5,0.2,Iris-setosa,cm
4,5,5.0,3.6,1.4,0.2,Iris-setosa,cm

**Выявление проблем: пропуски, дубликаты, выбросы, противоречивые и «странные» значения.**

In [8]:
df.dtypes

id                   int64
sepal_length_cm        str
sepal_width_cm     float64
petal_length_cm    float64
petal_width_cm     float64
species                str
unit                   str
dtype: object

In [9]:
df.duplicated().sum()

np.int64(14)

In [10]:
df['sepal_length_cm'].unique()

<StringArray>
[       '??', 'very_long',         nan,       '4.6',       '5.0',       '5.4',
       '4.4',       '4.9',       '4.8',       '4.3',       '5.8',       '5.7',
       '5.1',       '5.2',       '4.7',       '5.5',       '4.5',       '5.3',
       '7.0',       '6.4',       '6.9',       '6.3',       '6.6',       '6.1',
       '5.6',       '6.7',       '6.2',       '5.9',       '6.8',       '6.0',
       '6.5',       '7.6',       '7.3',       '7.2',       '7.7',       '7.4',
       '7.9',      '62.0',      '67.0',      '63.0',      '73.0',      '68.0',
      '61.0',      '57.0',      '46.0',      '65.0',      '64.0']
Length: 47, dtype: str

In [11]:
df['species'].unique()

<StringArray>
[    'Iris-setosa',          'setsoa',         'unknown', 'Iris-versicolor',
  'Iris-virginica',      'virginica ',     'versi color']
Length: 7, dtype: str

In [12]:
df['unit'].unique()

<StringArray>
['cm', 'mm']
Length: 2, dtype: str

## **Очистка данных**

Удаление или объединение дубликатов.

In [13]:
def clean_data(df):
    # Drop duplicate rows across all columns
    df = df.drop_duplicates()
    return df

df = clean_data(df.copy())
df.duplicated().sum()

np.int64(0)

Обработка пропущенных значений: удаление строк/столбцов или заполнение статистическими и/или модельными методами.

In [14]:
df.head()

,id,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,species,unit
0,1,??,3.5,1.4,0.2,Iris-setosa,cm
1,2,very_long,3.0,1.4,0.2,Iris-setosa,cm
2,3,NaN,3.2,1.3,0.2,Iris-setosa,cm
3,4,4.6,3.1,1.5,0.2,Iris-setosa,cm
4,5,5.0,3.6,1.4,0.2,Iris-setosa,cm

In [15]:
def clean_data(df):
    df = df.iloc[2:]
    # Replace missing values with the most common value of each column in: 'sepal_length_cm'
    df = df.fillna({'sepal_length_cm': df['sepal_length_cm'].mode()[0]})
    # Replace missing values with the median of each column in: 'petal_width_cm'
    df = df.fillna({'petal_width_cm': df['petal_width_cm'].median()})
    # Replace missing values with the median of each column in: 'petal_length_cm'
    df = df.fillna({'petal_length_cm': df['petal_length_cm'].median()})
    return df

df_clean = clean_data(df.copy())
df_clean.head()

,id,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,species,unit
2,3,5.0,3.2,1.3,0.2,Iris-setosa,cm
3,4,4.6,3.1,1.5,0.2,Iris-setosa,cm
4,5,5.0,3.6,1.4,0.2,Iris-setosa,cm
5,6,5.4,3.9,1.7,0.4,setsoa,cm
6,7,4.6,3.4,1.4,0.3,Iris-setosa,cm

In [16]:
df_clean['species'].unique()

<StringArray>
[    'Iris-setosa',          'setsoa',         'unknown', 'Iris-versicolor',
  'Iris-virginica',      'virginica ',     'versi color']
Length: 7, dtype: str

In [17]:
df_clean['species'] = df_clean['species'].replace({
    'Iris-setosa': 'iris-setosa',
    'setsoa': 'iris-setosa',
    'Iris-versicolor': 'iris-versicolor',
    'Iris-virginica': 'iris-virginica',
    'virginica ': 'iris-virginica',
    'versi color': 'iris-versicolor'
})
df_clean['species'].unique()

<StringArray>
['iris-setosa', 'unknown', 'iris-versicolor', 'iris-virginica']
Length: 4, dtype: str

Обработка выбросов и шума: фильтрация, обрезка, замена, устойчивые оценки.

## **Преобразование и нормализация признаков**

In [31]:
df_clean.head()

,id,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,species,unit
2,3,5.0,3.2,1.3,0.2,iris-setosa,cm
3,4,4.6,3.1,1.5,0.2,iris-setosa,cm
4,5,5.0,3.6,1.4,0.2,iris-setosa,cm
5,6,5.4,3.9,1.7,0.4,iris-setosa,cm
6,7,4.6,3.4,1.4,0.3,iris-setosa,cm

Приведение типов

In [22]:
df_clean.dtypes

id                   int64
sepal_length_cm        str
sepal_width_cm     float64
petal_length_cm    float64
petal_width_cm     float64
species                str
unit                   str
dtype: object

In [26]:
df_clean['sepal_length_cm'] = df_clean['sepal_length_cm'].astype(float)

Масштабирование числовых признаков

In [30]:
num_cols = df_clean.select_dtypes(exclude='object').columns
num_cols

Index(['id', 'sepal_length_cm', 'sepal_width_cm', 'petal_length_cm',
       'petal_width_cm'],
      dtype='str')

Кодирование категориальных признаков

In [32]:
df_clean.shape

(169, 7)

In [33]:
df_clean = pd.get_dummies(df_clean)
df_clean.shape

(169, 11)

## **Сокращение и отбор признаков**

In [34]:
df_clean.columns

Index(['id', 'sepal_length_cm', 'sepal_width_cm', 'petal_length_cm',
       'petal_width_cm', 'species_iris-setosa', 'species_iris-versicolor',
       'species_iris-virginica', 'species_unknown', 'unit_cm', 'unit_mm'],
      dtype='str')

In [35]:
X = df_clean.drop(columns=['id', 'unit_mm', 'unit_cm', 'petal_length_cm'])
y = df_clean['petal_length_cm']

## **EDA (Разведочный анализ данных)**

## **Финальная подготовка к обучению**

Разделение на train/validation/test.

In [36]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

Автоматизация всех шагов предобработки (создания конвейера - pipeline).

In [37]:
from sklearn.linear_model import LinearRegression

# Building Model
model = LinearRegression()
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

In [38]:
y_pred.shape

(56,)

In [39]:
from sklearn.metrics import r2_score, mean_squared_error

print("R^2 score:", r2_score(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))

R^2 score: 0.9867589170022051
MSE: 1.5197378698518669