# pandas1

In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

# Обзор

In [40]:
data = {
    "year": [
        2022, 2022, 2022, 2022,
        2023, 2023, 2023, 2023,
        2024, 2024
    ],
    "crop": [
        "wheat", "barley", "corn", "wheat",
        "wheat", "barley", "corn", "wheat",
        "wheat", "corn"
    ],
    "yield_t_per_ha": [
        3.2, 2.8, 5.0, 3.0,
        3.5, 2.9, 5.2, 2.7,
        3.3, 5.1
    ],
    "region": [
        "Central", "Central", "Central", "North",
        "South", "South", "South", "North",
        "North", "South"
    ]
}

df_yield = pd.DataFrame(data)
df_yield

   year    crop  yield_t_per_ha   region
0  2022   wheat             3.2  Central
1  2022  barley             2.8  Central
2  2022    corn             5.0  Central
3  2022   wheat             3.0    North
4  2023   wheat             3.5    South
5  2023  barley             2.9    South
6  2023    corn             5.2    South
7  2023   wheat             2.7    North
8  2024   wheat             3.3    North
9  2024    corn             5.1    South

In [41]:
df_yield.head()

   year    crop  yield_t_per_ha   region
0  2022   wheat             3.2  Central
1  2022  barley             2.8  Central
2  2022    corn             5.0  Central
3  2022   wheat             3.0    North
4  2023   wheat             3.5    South

In [42]:
df_yield.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   year            10 non-null     int64
 1   crop            10 non-null     str
 2   yield_t_per_ha  10 non-null     float64
 3   region          10 non-null     str
dtypes: float64(1), int64(1), str(2)
memory usage: 452.0 bytes

In [43]:
df_yield.describe()

              year  yield_t_per_ha
count    10.000000       10.000000
mean   2022.800000        3.670000
std       0.788811        1.015491
min    2022.000000        2.700000
25%    2022.000000        2.925000
50%    2023.000000        3.250000
75%    2023.000000        4.625000
max    2024.000000        5.200000

# Работа со столбцами

In [44]:
df_yield['crop']

0     wheat
1    barley
2      corn
3     wheat
4     wheat
5    barley
6      corn
7     wheat
8     wheat
9      corn
Name: crop, dtype: str

In [45]:
df_yield[['year', 'yield_t_per_ha']]

   year  yield_t_per_ha
0  2022             3.2
1  2022             2.8
2  2022             5.0
3  2022             3.0
4  2023             3.5
5  2023             2.9
6  2023             5.2
7  2023             2.7
8  2024             3.3
9  2024             5.1

In [46]:
df_yield.loc[0]

year                 2022
crop                wheat
yield_t_per_ha        3.2
region            Central
Name: 0, dtype: object

In [47]:
df_yield.iloc[[2, 7]]

   year   crop  yield_t_per_ha   region
2  2022   corn             5.0  Central
7  2023  wheat             2.7    North

# Фильтрация данных

In [48]:
df_yield[df_yield['crop'] == 'wheat']

   year   crop  yield_t_per_ha   region
0  2022  wheat             3.2  Central
3  2022  wheat             3.0    North
4  2023  wheat             3.5    South
7  2023  wheat             2.7    North
8  2024  wheat             3.3    North

In [49]:
df_yield[df_yield['yield_t_per_ha'] > 3.0]

   year   crop  yield_t_per_ha   region
0  2022  wheat             3.2  Central
2  2022   corn             5.0  Central
4  2023  wheat             3.5    South
6  2023   corn             5.2    South
8  2024  wheat             3.3    North
9  2024   corn             5.1    South

In [50]:
df_yield[(df_yield['year'] == 2023) & (df_yield['region'] == "South")]

   year    crop  yield_t_per_ha region
4  2023   wheat             3.5  South
5  2023  barley             2.9  South
6  2023    corn             5.2  South

In [51]:
df_yield.query("crop == 'wheat'")

   year   crop  yield_t_per_ha   region
0  2022  wheat             3.2  Central
3  2022  wheat             3.0    North
4  2023  wheat             3.5    South
7  2023  wheat             2.7    North
8  2024  wheat             3.3    North

In [52]:
df_yield.query("yield_t_per_ha > 3.0")

   year   crop  yield_t_per_ha   region
0  2022  wheat             3.2  Central
2  2022   corn             5.0  Central
4  2023  wheat             3.5    South
6  2023   corn             5.2    South
8  2024  wheat             3.3    North
9  2024   corn             5.1    South

In [53]:
df_yield.query("year == 2023 & region == 'South'")

   year    crop  yield_t_per_ha region
4  2023   wheat             3.5  South
5  2023  barley             2.9  South
6  2023    corn             5.2  South

# (!) Сортировка и вычисление новых столбцов

In [54]:
df_yield['yield_t_per_ha'].sort_values(ascending=False)

6    5.2
9    5.1
2    5.0
4    3.5
8    3.3
0    3.2
3    3.0
5    2.9
1    2.8
7    2.7
Name: yield_t_per_ha, dtype: float64

In [55]:
df_yield.sort_values(by=["year", "yield_t_per_ha"], ascending=[True, False])

   year    crop  yield_t_per_ha   region
2  2022    corn             5.0  Central
0  2022   wheat             3.2  Central
3  2022   wheat             3.0    North
1  2022  barley             2.8  Central
6  2023    corn             5.2    South
4  2023   wheat             3.5    South
5  2023  barley             2.9    South
7  2023   wheat             2.7    North
9  2024    corn             5.1    South
8  2024   wheat             3.3    North

# Новый столбец "урожайность в ц/га"

In [56]:
df_yield['yield_c_per_ha'] = df_yield['yield_t_per_ha'].apply(lambda x: x * 10)

In [57]:
df_yield['yield_c_per_ha']

0    32.0
1    28.0
2    50.0
3    30.0
4    35.0
5    29.0
6    52.0
7    27.0
8    33.0
9    51.0
Name: yield_c_per_ha, dtype: float64

# (!) Средняя урожайность

In [ ]:
def calculate_mean(cols: str | list[str]):
    print(df_yield.groupby(cols)['yield_t_per_ha'].mean())

In [59]:
calculate_mean('crop')

crop
barley    2.85
corn      5.10
wheat     3.14
Name: yield_t_per_ha, dtype: float64

In [60]:
calculate_mean('region')

region
Central    3.666667
North      3.000000
South      4.175000
Name: yield_t_per_ha, dtype: float64

In [61]:
calculate_mean(['year', 'crop'])

year  crop
2022  barley    2.8
      corn      5.0
      wheat     3.1
2023  barley    2.9
      corn      5.2
      wheat     3.1
2024  corn      5.1
      wheat     3.3
Name: yield_t_per_ha, dtype: float64

# (!) Сводная таблица

In [62]:
pivot = pd.pivot_table(
    df_yield,
    values="yield_t_per_ha",
    index="region",
    columns="crop",
    aggfunc="mean"
)
pivot

crop     barley  corn  wheat
region
Central     2.8  5.00    3.2
North       NaN   NaN    3.0
South       2.9  5.15    3.5